### ISSUE TITLE
keepKeys控制权

### ISSUE THREAD

**Issue by Reasno** [fangx-packages/php-enum#1]
https://github.com/fangx-packages/php-enum/blob/ebb8542a3c19d4917b087e2cb836c3d092987d02/src/Manager.php#L80

这个地方，与其将unFormat特殊化，不如在format里加入一个方法来控制是否keepKeys把。

**Comment by nfangxu** [comment]
添加了一个 KeepKeysFormat 的 interface, 用来处理这个东西 [TAG-v1.3.2](https://github.com/fangx-packages/php-enum/tree/v1.3.2)
